version: '3'

services:
  vite:
    build:
      context: ./client
    ports:
      - 4173:4173

  nginx:
    build:
      context: ./nginx
    ports:
      - 4343:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - vite

